spring.application.name=exemplo2

# URL de conexão do banco de dados
spring.datasource.url=jdbc:h2:mem:bancoteste

# Define o usuario padrão
spring.datasource.username=sa
# Define a senha do usuario padrão (vazia por padrão)
spring.datasource.password=

# Habilita o console do h2
spring.h2.console.enable=true
# Define a URL do console
spring.h2.console.path=/h2-console

# Para o h2 funcionar no codespaces
spring.h2.console.settings.web-allow-others=true
server.forward-headers-strategy=framework

# Configura o JPA para atualizar a estrutura do banco automaticamente baseados na classes do Java
spring.jpa.hibernate.ddl-auto=update